application: pvilla-backend
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "1h"

handlers:
- url: /styles
  static_dir: styles

- url: /img
  static_dir: img

- url: /js
  static_dir: js
  
- url: /
  static_files: index.html
  upload: index.html

- url: /api/.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest